server:
  port: 9000
spring:
  application:
    name: ad_gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /ab
  routes:
    sponsor:
      path: /ad_sponsor/**
      serviceId: eureka_client_ad_sponsor
      strip-prefix: false #不跳过前缀ad_sponsor  127.0.0.1:8080/ab/ad_sponsor/create/adPlan
#    search:
#      path: /ad_search/**
#      serviceId: eureka_client_ad_search
#      strip-prefix: false
